### ISSUE TITLE
ynab-api: Implement getting an Account by its ID

### ISSUE THREAD

**Issue by phrohdoh** [Phrohdoh/ynab-rs#14]
Similar to #4 and #13 we need to be able to get an `Account` by `id`.

**Comment by bgigous** [comment]
Good day.

I made a pull request here for this issue and for #15 in a PR (#17). Not sure if I did the PR "correctly" but waiting for review.

**Comment by phrohdoh** [comment]
This can be closed given #17 has been merged.
