### ISSUE TITLE
Implement getting a Category by its ID

### ISSUE THREAD

**Issue by Deadairx** [Phrohdoh/ynab-rs#4]
We need the `ynab-api` component's `Client` to allow consuming code to fetch a single category by its ID.

The function's return type should be `types::Result<ynab_types::Category>`.

`Category` (in the `ynab_types` component) is already defined as:

```rust
pub struct Category {
    pub id: String,
    pub category_group_id: String,
    pub name: String,
    pub hidden: bool,
    pub original_category_group_id: String,
    pub note: String,
    pub budgeted: i64,
    pub activity: i64,
    pub balance: i64,
    pub goal_type: String,
    pub goal_creation_month: String,
    pub goal_target: i64,
    pub goal_target_month: String,
    pub goal_percentage_complete: i64,
    pub deleted: bool,
}
```

But https://api.youneedabudget.com/v1#/Categories/getCategoryById does not return this shape directly, it returns our `Category` shape wrapped in a parent "data" property (which is what `ynab_api::types::Response` is), so you will need to define an intermediate struct (named `Inner`) that you deserialize the response JSON into, then return the inner data to match the function signature so consuming code is always receiving the actual values they care about not the intermediate shapes.

Use `Client::get_all_scheduled_transactions` as reference.

**Comment by phrohdoh** [comment]
This was done in #6 🎉 thanks @Deadairx!
